spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangchao123321/config-repo
          username: 244067166@qq.com
          password: 3b9d4saA
  rabbitmq:
    host: 140.143.163.212
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"




